<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIGEFES.LimpaIntra\SIGEFES.LimpaIntra\SIGEFES.LimpaIntra.csproj" />
  </ItemGroup>

</Project>
